version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "swift"
    versioning-strategy: auto
    open-pull-requests-limit: 10
    rebase-strategy: auto
    groups:
      dependencies:
        patterns:
          - "*" 
